version: '2' # sử dụng version 2

services:
  freepbx-app: # đặt tên dịch vụ container
    # thiết lập tên cho container sau khi hoàn tất 
    container_name: freepbx-app 
    # tự dộng tìm dến file Dockerfile và xây dựng chúng
    build: . 
    # mở port và ánh xạ port ra ngoài
    ports: 
      - 8080:80
      - 5060:5060/udp
      - 5160:5160/udp
      - 18000-18100:18000-18100/udp
      - 4445:4445
#       - 10000-65000:10000-65000/udp
    # Ánh xạ thử mục ổ đĩa
    volumes: 
      - ./certs:/certs
      - ./data:/data
      - ./logs:/var/log
      - ./data/www:/var/www/html
    # thiết lập biến môi trường trung gian
    environment: 
      - VIRTUAL_HOST=hostname.example.com
      - VIRTUAL_NETWORK=host
      - VIRTUAL_PORT=80
      - RTP_START=10000
      - RTP_FINISH=20000
      ## Sử dụng cho Máy chủ MySQL Bên ngoài
      #dbs được thiết lập bên dưới sd mariabd - mysql 
      - DB_HOST=freepbx-db 
      - DB_PORT=3306
      - DB_NAME=asterisk
      - DB_USER=asterisk
      - DB_PASS=asteriskpass
      # tiến trình sau khi hoàn tất sẽ restart
    restart: always 
    networks:
      # sd mạng bridge
      - freepbx-network 
    privileged: true
# database host
  freepbx-db:
    container_name: freepbx-db
    image: tiredofit/mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    # thiết lập môi trường dbs bên ngoài
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=asterisk
      - MYSQL_USER=asterisk
      - MYSQL_PASSWORD=asteriskpass
    networks:
      - freepbx-network
# dữ liệu dbs backup 
  freepbx-db-backup:
    container_name: freepbx-db-backup
    image: tiredofit/db-backup
    links:
     - freepbx-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - ZABBIX_HOSTNAME=freepbx-db-backup
      - DB_HOST=freepbx-db
      - DB_TYPE=mariadb
      - DB_NAME=asterisk
      - DB_USER=asterisk
      - DB_PASS=asteriskpass
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    networks:
      - freepbx-network
    restart: always

    # đang đề xuất thêm Zabix làm monitor để giám sát lưu lượng cân bằng tốt hơn 
 # thiết lập mạng riêng cho vùng chứa sd card mạng bridge    
networks:
  freepbx-network:
    driver: bridge
