# Note that: Tệp docker-compose này sẽ cho thấy tất cả các lệnh của docker-compose sẽ được thực thi như nào
version: '2' # sử dụng version 2

services:
# /============================================FreePBX-Asterisk==================================================\
  freepbx-app: # đặt tên dịch vụ container
    # thiết lập tên cho container sau khi hoàn tất 
    container_name: freepbx-app 
    # tự dộng tìm dến file Dockerfile và xây dựng chúng, ví dụ : build: .. hoặc cách như bên dưới
    build: 
      context: .. # chỉ mục đến thư mục chứa Dockerfile
      dockerfile: Dockerfile # chỉ áp dụng với tập tin Dockerfile
    # mở port và ánh xạ port ra ngoài hay còn gọi là map port còn : là khoảng cách phân chia rõ 2 bên,
    # 1 bên là localhost cho máy vật lý vị trí cánh trái và 1 bên là host cho máy ảo tức thằng container vị trí cánh phải
    # ví dụ : localhost:virtualhost
    ports: 
      - 8080:8080
      - 5060:5060/udp
      - 5160:5160/udp
      - 18000-18100:18000-18100/udp
      - 4445:4445
      - 55000:55000
      - 4000:4000
    # Ánh xạ thử mục ổ đĩa hay còn gọi là mount map, có 2 dạng : 1 là bind mount và 2 là vollumn
    # phân biệt: bind mount không được quản lý bởi docker còn volume dành cho docker
    # thứ 2: volumn dành cho virtualhót, docker container còn bind mount là dành cho thiết bị vật lý như windows macos, linux 
    volumes: 
      - ./certs:/certs
      - ./data:/data
      - ./logs:/var/log
      - ./data/www:/var/www/html
    # Thêm các biến môi trường từ một tệp. Có thể là một giá trị đơn lẻ hoặc một danh sách, thêm cho đủ bộ ...
    env_file: .env
    environment: 
      - ADMIN_DIRECTORY=/admin
      - VIRTUAL_HOST=hostname.example.com
      - VIRTUAL_NETWORK=host
      - VIRTUAL_PORT=80
      - HTTP_PORT=8080
      - HTTPS_PORT=1443
      - RTP_START=10000
      - RTP_FINISH=65000
      - CHOKIDAR_USEPOLLING=true
      # DATABASSES
      # kết nối tới databases: mysql -uasterisk -p'asterisk' -D asterisk -h freepbx-db
      - DB_EMBEDDED=FALSE
      # Dịch vụ này phụ thuộc vào mariadb-mýsql. Bắt đầu điều đó đầu tiên
      # Dịch vụ host ở đây cho phép chúng ta nhảy đến môi trường container databases
      - DB_HOST=freepbx-db 
      - ROOT_PASS=password
      - DB_NAME=asterisk
      - DB_USER=asterisk
      - DB_PASS=asterisk
      - DB_PORT=3306
    # tiến trình sau khi hoàn tất sẽ restart
    restart: always 
    networks:
      # sd mạng bridge
      freepbx-network:
        ipv4_address: 172.20.0.6
    extra_hosts:
    # Ánh xạ địa chỉ ip locahost vs virutual host : sd cli như sau --add-host
    # cú pháp show ip container mặc định 172.17.0.1
    # ip addr show | grep "\binet\b.*\docker0\b" | awk '{print $2}' | cut -d '/' -f 1
      - "host.docker.internal:172.17.0.1"
    # Kiểm tra vùng chứa xem thế nào
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    privileged: true
# /============================================MARIADB-MySQL==================================\    
  # Database host
  # Sử dụng cho Máy chủ MySQL Bên ngoài
  # dbs được thiết lập bên dưới sd mariabd - mysql 
  # mariabd có sẵn không hỗ trợ tập tin .sql
  freepbx-db:
    container_name: freepbx-db
    image: tiredofit/mariadb
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      # tập tin dưới dây cho phép khởi tạo hay chỉnh sửa cấu hình trong databases
      # chú ý: do sử dụng images có sẵn, ở đây không hỗ trợ tệp sql
      - ../mysql/30_init_db/:/etc/services.available/30_init_db/
    # thiết lập môi trường dbs bên ngoài
    environment:
      # % == any host tức là remote với bất kỳ ip, ngoài ra có thể cho cố định ip nhưng đây là bản kiểm thử nên để any
      # thiết lập cấu hình databases
      - MYSQL_ROOT_HOST=%
      - DB_NAME=asterisk
      - DB_USER=asterisk
      - DB_PASS=asterisk
      - ROOT_PASS=password
      - DB_BACKUP=TRUE
    networks:
      freepbx-network:
        ipv4_address: 172.20.0.5
# /============================================MARIADB-MySQL-BACKUP==================================\    
  freepbx-db-backup:
    container_name: freepbx-db-backup
    image: tiredofit/db-backup
    links:
     - freepbx-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - ZABBIX_HOSTNAME=freepbx-db-backup
      - DB_HOST=freepbx-db
      - DB_TYPE=mariadb
      - DB_NAME=asterisk
      - DB_USER=asterisk
      - DB_PASS=asteriskpass
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    networks:
      freepbx-network:
        ipv4_address: 172.20.0.3
    restart: always
# /============================================NETWORK=========================================\    
# thiết lập mạng cho container
networks:
  freepbx-network: # tên mạng
    ipam:
      config:
        - subnet: 172.20.0.0/24 # /24 chỉ subnet mask phân chia cho 254 thiết bị trong cùng mạng nội bộ chứa container
          gateway: 172.20.0.1 # đường đi bao giờ cũng phải đúng, sai lệch là ko lên hình
        